import { motionTokens } from './motionTokens.js'

export const moneyOSThemeClass = 'money-os'
export const defaultMoneyOSTheme = 'minimalWhite'

export const moneyOSThemeOptions = Object.freeze([
  Object.freeze({
    id: 'minimalWhite',
    label: 'Default Clean',
    detail: 'Bright white surfaces, crisp spacing, and normal system typography.',
    personality: 'Clean minimal daily page',
  }),
  Object.freeze({
    id: 'classic',
    label: 'Notebook',
    detail: 'Cream ruled paper with blue and red pen handwriting across the whole app.',
    personality: 'Blue-and-red pen notebook',
  }),
  Object.freeze({
    id: 'ledgerPro',
    label: 'Ledger Pro',
    detail: 'Accounting register rows, professional document font, precise spacing.',
    personality: 'Professional money register',
  }),
  Object.freeze({
    id: 'receipt',
    label: 'Receipt',
    detail: 'Thermal paper texture, compact receipt mono font, receipt-style entries.',
    personality: 'Fast store-receipt notebook',
  }),
  Object.freeze({
    id: 'code',
    label: 'Code Ledger',
    detail: 'Terminal paper, syntax colors, monospaced code text, and editor-like panels.',
    personality: 'Developer console ledger',
  }),
  Object.freeze({
    id: 'blueRegister',
    label: 'Blue Register',
    detail: 'Cool blue register pages with textbook-style serif typography.',
    personality: 'Textbook register page',
  }),
  Object.freeze({
    id: 'emerald',
    label: 'Mint Calm',
    detail: 'Fresh green accents, rounded friendly font, and relaxed readable spacing.',
    personality: 'Fresh premium daily page',
  }),
  Object.freeze({
    id: 'midnight',
    label: 'Midnight Focus',
    detail: 'Dark focus surfaces with crisp product typography and restrained accents.',
    personality: 'Focused evening daily page',
  }),
  Object.freeze({
    id: 'sunset',
    label: 'Warm Paper',
    detail: 'Warm editorial paper, soft contrast, and bookish serif calm.',
    personality: 'Friendly premium daily page',
  }),
])

export const moneyOSThemeIds = Object.freeze(moneyOSThemeOptions.map((theme) => theme.id))

export const moneyOSThemeAliases = Object.freeze({
  blueRegister: 'blueRegister',
  brownJournal: 'classic',
  coder: 'code',
  code: 'code',
  emerald: 'emerald',
  executive: 'ledgerPro',
  minimal: 'minimalWhite',
  minimalWhite: 'minimalWhite',
  midnight: 'midnight',
  navy: 'classic',
  sunset: 'sunset',
  terminal: 'code',
  vintageDiary: 'classic',
})

export function normalizeMoneyOSTheme(theme) {
  const themeId = moneyOSThemeAliases[theme] || theme
  return moneyOSThemeIds.includes(themeId) ? themeId : defaultMoneyOSTheme
}

export const moneyOSThemeV2 = Object.freeze({
  classic: Object.freeze({
    label: 'Notebook',
    experience: 'daily-money-notebook',
    personality: 'Premium notebook with cream paper, ruled lines, and blue/red pen handwriting across the app.',
    paper: 'var(--theme-paper)',
    ink: 'var(--theme-text)',
    lines: 'var(--theme-line)',
    accent: 'var(--theme-accent)',
    cards: 'var(--theme-card)',
    borders: 'var(--theme-border)',
    icons: 'var(--theme-icon)',
    emptyState: 'var(--theme-empty)',
    typography: Object.freeze({
      heading: 'var(--font-notebook-accent)',
      date: 'var(--font-notebook-accent)',
      section: 'var(--font-notebook-accent)',
      body: 'var(--font-notebook-readable)',
      amount: 'var(--font-notebook-readable)',
    }),
    texture: Object.freeze({
      paper: 'ruled',
      card: 'notebook-card',
      ledgerRows: 'page-lines',
      dialogs: 'paper-sheet',
      exports: 'notebook-pages',
    }),
    components: Object.freeze({
      cards: 'lined-paper',
      ledgerRows: 'notebook-page',
      buttons: 'ink-tabs',
      fab: 'ink-button',
      icons: 'pen-line',
      emptyStates: 'fresh-page',
      illustrations: 'paper-corners',
    }),
    motion: Object.freeze({
      profile: 'calm-writing',
      paper: 'gentle-page-rise',
      ink: 'soft-line-appear',
      lineInsertion: 'written-line',
      themeSwitch: 'warm-crossfade',
    }),
    rhythm: Object.freeze({
      verticalSpacing: '18px',
      lineHeight: '32px',
      sectionSpacing: '24px',
      dividerThickness: '1px',
      cardDensity: 'comfortable',
    }),
    divider: Object.freeze({
      style: 'ink-rule',
      thickness: '1px',
    }),
    shape: Object.freeze({
      cardRadius: '8px',
      buttonRadius: '8px',
      sheetRadius: '14px',
    }),
    shadow: Object.freeze({
      style: 'soft-page',
      depth: 'soft',
    }),
    spacing: Object.freeze({
      density: 'comfortable',
      rhythm: 'ruled-page',
    }),
    paperTexture: 'warm-ruled-paper',
    exportStyle: 'premium-journal-page',
    copy: Object.freeze({
      homeReady: "Today's page is ready.",
      homeFinished: "You've finished today's notebook.",
      emptyLedger: 'This page is waiting for your first expense.',
      emptyHome: 'This page is waiting for your first expense.',
      emptyBorrowLend: 'This borrow/lend page is waiting for a name.',
      emptyTrip: 'This trip page is waiting for people.',
      pageFooter: 'FBPLY daily money notebook',
      monthNotebook: 'Current month notebook',
    }),
    exportMode: Object.freeze({
      singlePage: 'image',
      multiPage: 'pdf',
    }),
    motionIntensity: 'medium',
  }),
  minimalWhite: Object.freeze({
    label: 'Default Clean',
    experience: 'clean-daily-page',
    personality: 'Clean normal daily money page with bright surfaces and system typography.',
    paper: 'var(--theme-paper)',
    ink: 'var(--theme-text)',
    lines: 'var(--theme-line)',
    accent: 'var(--theme-accent)',
    cards: 'var(--theme-card)',
    borders: 'var(--theme-border)',
    icons: 'var(--theme-icon)',
    emptyState: 'var(--theme-empty)',
    typography: Object.freeze({
      heading: 'var(--font-primary-ui)',
      date: 'var(--font-primary-ui)',
      section: 'var(--font-primary-ui)',
      body: 'var(--font-primary-ui)',
      amount: 'var(--font-primary-ui)',
    }),
    texture: Object.freeze({
      paper: 'clean-paper',
      card: 'clean-card',
      ledgerRows: 'subtle-separators',
      dialogs: 'clean-sheet',
      exports: 'clean-report',
    }),
    components: Object.freeze({
      cards: 'clean-panels',
      ledgerRows: 'clean-row',
      buttons: 'clean-actions',
      fab: 'primary-pill',
      icons: 'simple-line',
      emptyStates: 'quiet-page',
      illustrations: 'simple-lines',
    }),
    motion: Object.freeze({
      profile: 'calm-clean',
      paper: 'soft-rise',
      ink: 'subtle-line-appear',
      lineInsertion: 'clean-row',
      themeSwitch: 'clean-crossfade',
    }),
    rhythm: Object.freeze({
      verticalSpacing: '16px',
      lineHeight: '30px',
      sectionSpacing: '22px',
      dividerThickness: '1px',
      cardDensity: 'comfortable',
    }),
    divider: Object.freeze({
      style: 'subtle-separator',
      thickness: '1px',
    }),
    shape: Object.freeze({
      cardRadius: '10px',
      buttonRadius: '10px',
      sheetRadius: '12px',
    }),
    shadow: Object.freeze({
      style: 'soft-clean',
      depth: 'low',
    }),
    spacing: Object.freeze({
      density: 'comfortable',
      rhythm: 'clean-page',
    }),
    paperTexture: 'clean-white-paper',
    exportStyle: 'clean-daily-page',
    copy: Object.freeze({
      homeReady: "Today's page is open.",
      homeFinished: "Today's page is complete.",
      emptyLedger: 'This page is waiting for your first expense.',
      emptyHome: 'This page has no expense lines yet.',
      emptyBorrowLend: 'No borrow/lend lines added yet.',
      emptyTrip: 'No split lines added yet.',
      pageFooter: 'FBPLY daily money notebook',
      monthNotebook: 'Monthly pages',
    }),
    exportMode: Object.freeze({
      singlePage: 'image',
      multiPage: 'pdf',
    }),
    motionIntensity: 'polished',
  }),
  ledgerPro: Object.freeze({
    label: 'Ledger Pro',
    experience: 'accounting-register',
    personality: 'Professional accounting register with document rows and restrained motion.',
    paper: 'var(--theme-paper)',
    ink: 'var(--theme-text)',
    lines: 'var(--theme-line)',
    accent: 'var(--theme-accent)',
    cards: 'var(--theme-card)',
    borders: 'var(--theme-border)',
    icons: 'var(--theme-icon)',
    emptyState: 'var(--theme-empty)',
    typography: Object.freeze({
      heading: 'var(--font-primary-ui)',
      date: 'var(--font-primary-ui)',
      section: 'var(--font-primary-ui)',
      body: 'var(--font-primary-ui)',
      amount: 'var(--font-primary-ui)',
    }),
    texture: Object.freeze({
      paper: 'register-paper',
      card: 'register-card',
      ledgerRows: 'register-separators',
      dialogs: 'document-sheet',
      exports: 'business-register',
    }),
    components: Object.freeze({
      cards: 'document-panels',
      ledgerRows: 'register-row',
      buttons: 'document-actions',
      fab: 'register-stamp',
      icons: 'business-line',
      emptyStates: 'empty-register',
      illustrations: 'folio-lines',
    }),
    motion: Object.freeze({
      profile: 'structured-register',
      paper: 'document-step',
      ink: 'precise-row-appear',
      lineInsertion: 'register-row',
      themeSwitch: 'document-fade',
    }),
    rhythm: Object.freeze({
      verticalSpacing: '14px',
      lineHeight: '30px',
      sectionSpacing: '20px',
      dividerThickness: '1px',
      cardDensity: 'efficient',
    }),
    divider: Object.freeze({
      style: 'register-separator',
      thickness: '1px',
    }),
    shape: Object.freeze({
      cardRadius: '6px',
      buttonRadius: '6px',
      sheetRadius: '8px',
    }),
    shadow: Object.freeze({
      style: 'document-shadow',
      depth: 'medium',
    }),
    spacing: Object.freeze({
      density: 'efficient',
      rhythm: 'ledger-register',
    }),
    paperTexture: 'structured-register-paper',
    exportStyle: 'professional-register',
    copy: Object.freeze({
      homeReady: "Today's page is open.",
      homeFinished: "Today's page is complete.",
      emptyLedger: 'No expense lines recorded yet.',
      emptyHome: 'This page has no expense lines yet.',
      emptyBorrowLend: 'No borrow/lend lines added.',
      emptyTrip: 'No split lines added.',
      pageFooter: 'FBPLY daily record',
      monthNotebook: 'Monthly pages',
    }),
    exportMode: Object.freeze({
      singlePage: 'image',
      multiPage: 'pdf',
    }),
    motionIntensity: 'polished',
  }),
  receipt: Object.freeze({
    label: 'Receipt',
    experience: 'thermal-receipt',
    personality: 'Compact thermal receipt with quick scanning and crisp totals.',
    paper: 'var(--theme-paper)',
    ink: 'var(--theme-text)',
    lines: 'var(--theme-line)',
    accent: 'var(--theme-accent)',
    cards: 'var(--theme-card)',
    borders: 'var(--theme-border)',
    icons: 'var(--theme-icon)',
    emptyState: 'var(--theme-empty)',
    typography: Object.freeze({
      heading: 'var(--font-monospace)',
      date: 'var(--font-monospace)',
      section: 'var(--font-monospace)',
      body: 'var(--font-monospace)',
      amount: 'var(--font-monospace)',
    }),
    texture: Object.freeze({
      paper: 'thermal-paper',
      card: 'receipt-strip',
      ledgerRows: 'receipt-rows',
      dialogs: 'receipt-sheet',
      exports: 'receipt-roll',
    }),
    components: Object.freeze({
      cards: 'receipt-panels',
      ledgerRows: 'receipt-line-item',
      buttons: 'receipt-actions',
      fab: 'receipt-punch',
      icons: 'compact-line',
      emptyStates: 'blank-receipt',
      illustrations: 'perforated-edge',
    }),
    motion: Object.freeze({
      profile: 'fast-compact',
      paper: 'quick-slip',
      ink: 'snap-line-appear',
      lineInsertion: 'receipt-line',
      themeSwitch: 'quick-print',
    }),
    rhythm: Object.freeze({
      verticalSpacing: '10px',
      lineHeight: '24px',
      sectionSpacing: '14px',
      dividerThickness: '1px',
      cardDensity: 'compact',
    }),
    divider: Object.freeze({
      style: 'receipt-perforation',
      thickness: '1px',
    }),
    shape: Object.freeze({
      cardRadius: '4px',
      buttonRadius: '4px',
      sheetRadius: '4px',
    }),
    shadow: Object.freeze({
      style: 'receipt-slip',
      depth: 'low',
    }),
    spacing: Object.freeze({
      density: 'compact',
      rhythm: 'receipt-strip',
    }),
    paperTexture: 'thermal-receipt-paper',
    exportStyle: 'thermal-receipt',
    copy: Object.freeze({
      homeReady: "Today's receipt is ready.",
      homeFinished: "Today's receipt is complete.",
      emptyLedger: 'No receipts added today.',
      emptyHome: 'No receipts added for this selection.',
      emptyBorrowLend: 'No borrow/lend slips added.',
      emptyTrip: 'No trip receipts added.',
      pageFooter: 'FBPLY receipt copy',
      monthNotebook: 'Monthly receipt roll',
    }),
    exportMode: Object.freeze({
      singlePage: 'image',
      multiPage: 'pdf',
    }),
    motionIntensity: 'low',
  }),
  code: Object.freeze({
    label: 'Code Ledger',
    experience: 'developer-console-ledger',
    personality: 'Developer console ledger with terminal paper, syntax colors, and monospaced rhythm.',
    paper: 'var(--theme-paper)',
    ink: 'var(--theme-text)',
    lines: 'var(--theme-line)',
    accent: 'var(--theme-accent)',
    cards: 'var(--theme-card)',
    borders: 'var(--theme-border)',
    icons: 'var(--theme-icon)',
    emptyState: 'var(--theme-empty)',
    typography: Object.freeze({
      heading: 'var(--font-code)',
      date: 'var(--font-code)',
      section: 'var(--font-code)',
      body: 'var(--font-code)',
      amount: 'var(--font-code)',
    }),
    texture: Object.freeze({
      paper: 'terminal-paper',
      card: 'editor-panel',
      ledgerRows: 'syntax-rows',
      dialogs: 'terminal-sheet',
      exports: 'code-export',
    }),
    components: Object.freeze({
      cards: 'editor-panels',
      ledgerRows: 'code-line',
      buttons: 'terminal-actions',
      fab: 'run-button',
      icons: 'syntax-line',
      emptyStates: 'empty-console',
      illustrations: 'prompt-lines',
    }),
    motion: Object.freeze({
      profile: 'console-boot',
      paper: 'terminal-slide',
      ink: 'syntax-highlight',
      lineInsertion: 'new-log-line',
      themeSwitch: 'editor-swap',
    }),
    rhythm: Object.freeze({
      verticalSpacing: '12px',
      lineHeight: '26px',
      sectionSpacing: '18px',
      dividerThickness: '1px',
      cardDensity: 'efficient',
    }),
    divider: Object.freeze({
      style: 'terminal-rule',
      thickness: '1px',
    }),
    shape: Object.freeze({
      cardRadius: '6px',
      buttonRadius: '6px',
      sheetRadius: '8px',
    }),
    shadow: Object.freeze({
      style: 'terminal-glow',
      depth: 'medium',
    }),
    spacing: Object.freeze({
      density: 'efficient',
      rhythm: 'editor-lines',
    }),
    paperTexture: 'terminal-editor-paper',
    exportStyle: 'code-ledger',
    copy: Object.freeze({
      homeReady: "Today's money log is ready.",
      homeFinished: "Today's money log is committed.",
      emptyLedger: 'No expense logs recorded yet.',
      emptyHome: 'This run has no expense logs yet.',
      emptyBorrowLend: 'No borrow/lend commits yet.',
      emptyTrip: 'No split logs added yet.',
      pageFooter: 'FBPLY code ledger',
      monthNotebook: 'Monthly commit log',
    }),
    exportMode: Object.freeze({
      singlePage: 'image',
      multiPage: 'pdf',
    }),
    motionIntensity: 'polished',
  }),
})

const moneyOSThemeExperienceAliases = Object.freeze({
  blueRegister: 'ledgerPro',
  emerald: 'ledgerPro',
  midnight: 'ledgerPro',
  sunset: 'classic',
})

export function getMoneyOSThemeExperience(theme = defaultMoneyOSTheme) {
  const themeId = normalizeMoneyOSTheme(theme)
  const experienceThemeId = moneyOSThemeV2[themeId] ? themeId : (moneyOSThemeExperienceAliases[themeId] || defaultMoneyOSTheme)
  return moneyOSThemeV2[experienceThemeId] || moneyOSThemeV2[defaultMoneyOSTheme]
}

export const moneyOSTokens = Object.freeze({
  themeName: 'FBPLY Money OS',
  colors: Object.freeze({
    primaryNavy: '#102A43',
    primaryNavyStrong: '#071A2E',
    accentBlue: '#2563EB',
    accentBlueSoft: '#DBEAFE',
    successGreen: '#16803C',
    successGreenSoft: '#DCFCE7',
    warningAmber: '#B45309',
    warningAmberSoft: '#FEF3C7',
    errorRed: '#B91C1C',
    errorRedSoft: '#FEE2E2',
    neutral50: '#F8FAFC',
    neutral100: '#F1F5F9',
    neutral200: '#E2E8F0',
    neutral500: '#64748B',
    neutral700: '#334155',
    neutral900: '#0F172A',
    surfaceBase: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    surfaceTint: '#EFF6FF',
  }),
  typography: Object.freeze({
    moneyDisplay: Object.freeze({ fontSize: '24px', lineHeight: '30px', fontWeight: 900 }),
    sectionTitle: Object.freeze({ fontSize: '22px', lineHeight: '28px', fontWeight: 850 }),
    cardTitle: Object.freeze({ fontSize: '15px', lineHeight: '20px', fontWeight: 850 }),
    body: Object.freeze({ fontSize: '15px', lineHeight: '23px', fontWeight: 500 }),
    caption: Object.freeze({ fontSize: '12px', lineHeight: '16px', fontWeight: 750 }),
    meta: Object.freeze({ fontSize: '12px', lineHeight: '16px', fontWeight: 800 }),
  }),
  spacing: Object.freeze({
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    page: '24px',
    card: '16px',
    rhythm: '8px',
  }),
  radius: Object.freeze({
    small: '4px',
    medium: '6px',
    large: '8px',
    card: '8px',
    sheet: '8px',
  }),
  shadows: Object.freeze({
    soft: '0 8px 22px rgba(15, 23, 42, 0.08)',
    medium: '0 14px 36px rgba(15, 23, 42, 0.12)',
  }),
  motion: Object.freeze({
    durationFast: `${motionTokens.duration.fast}ms`,
    durationNormal: `${motionTokens.duration.normal}ms`,
    durationSlow: `${motionTokens.duration.slow}ms`,
    durationModal: `${motionTokens.duration.modal}ms`,
    durationCard: `${motionTokens.duration.card}ms`,
    durationNumberReveal: `${motionTokens.duration.numberReveal}ms`,
    durationHomeEntry: `${motionTokens.duration.homeEntry}ms`,
    durationLoader: `${motionTokens.duration.loader}ms`,
    durationAttention: `${motionTokens.duration.attention}ms`,
    durationSkeleton: `${motionTokens.duration.skeleton}ms`,
    delayHomeHeader: `${motionTokens.delay.homeHeader}ms`,
    delayHomeCards: `${motionTokens.delay.homeCards}ms`,
    delayNumberReveal: `${motionTokens.delay.numberReveal}ms`,
    delayQuickActions: `${motionTokens.delay.quickActions}ms`,
    delayRecentActivity: `${motionTokens.delay.recentActivity}ms`,
    delayStagger: `${motionTokens.delay.stagger}ms`,
    delayCompactStagger: `${motionTokens.delay.compactStagger}ms`,
    easingStandard: motionTokens.easing.standard,
    easingDecelerate: motionTokens.easing.decelerate,
    easingSoftOut: motionTokens.easing.softOut,
    springGentle: motionTokens.spring.gentle,
    springSettle: motionTokens.spring.settle,
    springFirm: motionTokens.spring.firm,
    reducedMotion: motionTokens.reducedMotion,
    fast: `${motionTokens.duration.fast}ms ${motionTokens.easing.standard}`,
    normal: `${motionTokens.duration.normal}ms ${motionTokens.easing.standard}`,
  }),
})

export const moneyOSCssVariables = Object.freeze({
  '--mos-primary-navy': moneyOSTokens.colors.primaryNavy,
  '--mos-primary-navy-strong': moneyOSTokens.colors.primaryNavyStrong,
  '--mos-accent-blue': moneyOSTokens.colors.accentBlue,
  '--mos-accent-blue-soft': moneyOSTokens.colors.accentBlueSoft,
  '--mos-success-green': moneyOSTokens.colors.successGreen,
  '--mos-success-green-soft': moneyOSTokens.colors.successGreenSoft,
  '--mos-warning-amber': moneyOSTokens.colors.warningAmber,
  '--mos-warning-amber-soft': moneyOSTokens.colors.warningAmberSoft,
  '--mos-error-red': moneyOSTokens.colors.errorRed,
  '--mos-error-red-soft': moneyOSTokens.colors.errorRedSoft,
  '--mos-neutral-50': moneyOSTokens.colors.neutral50,
  '--mos-neutral-100': moneyOSTokens.colors.neutral100,
  '--mos-neutral-200': moneyOSTokens.colors.neutral200,
  '--mos-neutral-500': moneyOSTokens.colors.neutral500,
  '--mos-neutral-700': moneyOSTokens.colors.neutral700,
  '--mos-neutral-900': moneyOSTokens.colors.neutral900,
  '--mos-surface-base': moneyOSTokens.colors.surfaceBase,
  '--mos-surface-raised': moneyOSTokens.colors.surfaceRaised,
  '--mos-surface-muted': moneyOSTokens.colors.surfaceMuted,
  '--mos-surface-tint': moneyOSTokens.colors.surfaceTint,
  '--mos-font-money-size': moneyOSTokens.typography.moneyDisplay.fontSize,
  '--mos-font-money-line': moneyOSTokens.typography.moneyDisplay.lineHeight,
  '--mos-font-section-size': moneyOSTokens.typography.sectionTitle.fontSize,
  '--mos-font-section-line': moneyOSTokens.typography.sectionTitle.lineHeight,
  '--mos-font-card-title-size': moneyOSTokens.typography.cardTitle.fontSize,
  '--mos-font-card-title-line': moneyOSTokens.typography.cardTitle.lineHeight,
  '--mos-font-body-size': moneyOSTokens.typography.body.fontSize,
  '--mos-font-body-line': moneyOSTokens.typography.body.lineHeight,
  '--mos-font-caption-size': moneyOSTokens.typography.caption.fontSize,
  '--mos-font-caption-line': moneyOSTokens.typography.caption.lineHeight,
  '--mos-font-meta-size': moneyOSTokens.typography.meta.fontSize,
  '--mos-font-meta-line': moneyOSTokens.typography.meta.lineHeight,
  '--mos-space-xs': moneyOSTokens.spacing.xs,
  '--mos-space-sm': moneyOSTokens.spacing.sm,
  '--mos-space-md': moneyOSTokens.spacing.md,
  '--mos-space-lg': moneyOSTokens.spacing.lg,
  '--mos-space-xl': moneyOSTokens.spacing.xl,
  '--mos-space-page': moneyOSTokens.spacing.page,
  '--mos-space-card': moneyOSTokens.spacing.card,
  '--mos-space-rhythm': moneyOSTokens.spacing.rhythm,
  '--mos-radius-sm': moneyOSTokens.radius.small,
  '--mos-radius-md': moneyOSTokens.radius.medium,
  '--mos-radius-lg': moneyOSTokens.radius.large,
  '--mos-radius-card': moneyOSTokens.radius.card,
  '--mos-radius-sheet': moneyOSTokens.radius.sheet,
  '--mos-shadow-soft': moneyOSTokens.shadows.soft,
  '--mos-shadow-medium': moneyOSTokens.shadows.medium,
  '--motion-duration-fast': moneyOSTokens.motion.durationFast,
  '--motion-duration-normal': moneyOSTokens.motion.durationNormal,
  '--motion-duration-slow': moneyOSTokens.motion.durationSlow,
  '--motion-duration-modal': moneyOSTokens.motion.durationModal,
  '--motion-duration-card': moneyOSTokens.motion.durationCard,
  '--motion-duration-number-reveal': moneyOSTokens.motion.durationNumberReveal,
  '--motion-duration-home-entry': moneyOSTokens.motion.durationHomeEntry,
  '--motion-duration-loader': moneyOSTokens.motion.durationLoader,
  '--motion-duration-attention': moneyOSTokens.motion.durationAttention,
  '--motion-duration-skeleton': moneyOSTokens.motion.durationSkeleton,
  '--motion-delay-home-header': moneyOSTokens.motion.delayHomeHeader,
  '--motion-delay-home-cards': moneyOSTokens.motion.delayHomeCards,
  '--motion-delay-number-reveal': moneyOSTokens.motion.delayNumberReveal,
  '--motion-delay-quick-actions': moneyOSTokens.motion.delayQuickActions,
  '--motion-delay-recent-activity': moneyOSTokens.motion.delayRecentActivity,
  '--motion-delay-stagger': moneyOSTokens.motion.delayStagger,
  '--motion-delay-compact-stagger': moneyOSTokens.motion.delayCompactStagger,
  '--motion-ease-standard': moneyOSTokens.motion.easingStandard,
  '--motion-ease-decelerate': moneyOSTokens.motion.easingDecelerate,
  '--motion-ease-soft-out': moneyOSTokens.motion.easingSoftOut,
  '--mos-motion-fast': moneyOSTokens.motion.fast,
  '--mos-motion-normal': moneyOSTokens.motion.normal,
})
