export const moneyOSThemeClass = 'money-os'

export const moneyOSTokens = Object.freeze({
  themeName: 'FBPLY Money OS',
  colors: Object.freeze({
    primaryNavy: '#102A43',
    primaryNavyStrong: '#071A2E',
    accentBlue: '#2563EB',
    accentBlueSoft: '#DBEAFE',
    successGreen: '#16803C',
    successGreenSoft: '#DCFCE7',
    warningAmber: '#B45309',
    warningAmberSoft: '#FEF3C7',
    errorRed: '#B91C1C',
    errorRedSoft: '#FEE2E2',
    neutral50: '#F8FAFC',
    neutral100: '#F1F5F9',
    neutral200: '#E2E8F0',
    neutral500: '#64748B',
    neutral700: '#334155',
    neutral900: '#0F172A',
    surfaceBase: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    surfaceTint: '#EFF6FF',
  }),
  typography: Object.freeze({
    hero: Object.freeze({ fontSize: '34px', lineHeight: '40px', fontWeight: 850 }),
    section: Object.freeze({ fontSize: '22px', lineHeight: '28px', fontWeight: 800 }),
    body: Object.freeze({ fontSize: '15px', lineHeight: '23px', fontWeight: 500 }),
    caption: Object.freeze({ fontSize: '12px', lineHeight: '16px', fontWeight: 750 }),
  }),
  spacing: Object.freeze({
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
  }),
  radius: Object.freeze({
    small: '4px',
    medium: '6px',
    large: '8px',
  }),
  shadows: Object.freeze({
    soft: '0 8px 22px rgba(15, 23, 42, 0.08)',
    medium: '0 14px 36px rgba(15, 23, 42, 0.12)',
  }),
  motion: Object.freeze({
    fast: '140ms ease',
    normal: '220ms ease',
  }),
})

export const moneyOSCssVariables = Object.freeze({
  '--mos-primary-navy': moneyOSTokens.colors.primaryNavy,
  '--mos-primary-navy-strong': moneyOSTokens.colors.primaryNavyStrong,
  '--mos-accent-blue': moneyOSTokens.colors.accentBlue,
  '--mos-accent-blue-soft': moneyOSTokens.colors.accentBlueSoft,
  '--mos-success-green': moneyOSTokens.colors.successGreen,
  '--mos-success-green-soft': moneyOSTokens.colors.successGreenSoft,
  '--mos-warning-amber': moneyOSTokens.colors.warningAmber,
  '--mos-warning-amber-soft': moneyOSTokens.colors.warningAmberSoft,
  '--mos-error-red': moneyOSTokens.colors.errorRed,
  '--mos-error-red-soft': moneyOSTokens.colors.errorRedSoft,
  '--mos-neutral-50': moneyOSTokens.colors.neutral50,
  '--mos-neutral-100': moneyOSTokens.colors.neutral100,
  '--mos-neutral-200': moneyOSTokens.colors.neutral200,
  '--mos-neutral-500': moneyOSTokens.colors.neutral500,
  '--mos-neutral-700': moneyOSTokens.colors.neutral700,
  '--mos-neutral-900': moneyOSTokens.colors.neutral900,
  '--mos-surface-base': moneyOSTokens.colors.surfaceBase,
  '--mos-surface-raised': moneyOSTokens.colors.surfaceRaised,
  '--mos-surface-muted': moneyOSTokens.colors.surfaceMuted,
  '--mos-surface-tint': moneyOSTokens.colors.surfaceTint,
  '--mos-font-hero-size': moneyOSTokens.typography.hero.fontSize,
  '--mos-font-hero-line': moneyOSTokens.typography.hero.lineHeight,
  '--mos-font-section-size': moneyOSTokens.typography.section.fontSize,
  '--mos-font-section-line': moneyOSTokens.typography.section.lineHeight,
  '--mos-font-body-size': moneyOSTokens.typography.body.fontSize,
  '--mos-font-body-line': moneyOSTokens.typography.body.lineHeight,
  '--mos-font-caption-size': moneyOSTokens.typography.caption.fontSize,
  '--mos-font-caption-line': moneyOSTokens.typography.caption.lineHeight,
  '--mos-space-xs': moneyOSTokens.spacing.xs,
  '--mos-space-sm': moneyOSTokens.spacing.sm,
  '--mos-space-md': moneyOSTokens.spacing.md,
  '--mos-space-lg': moneyOSTokens.spacing.lg,
  '--mos-space-xl': moneyOSTokens.spacing.xl,
  '--mos-radius-sm': moneyOSTokens.radius.small,
  '--mos-radius-md': moneyOSTokens.radius.medium,
  '--mos-radius-lg': moneyOSTokens.radius.large,
  '--mos-shadow-soft': moneyOSTokens.shadows.soft,
  '--mos-shadow-medium': moneyOSTokens.shadows.medium,
  '--mos-motion-fast': moneyOSTokens.motion.fast,
  '--mos-motion-normal': moneyOSTokens.motion.normal,
})
