import { freeze } from './internal/freeze.js'
import { notebookMotion, notebookMotionCssVariables } from './motion.js'

export const notebookDesignSystemVersion = 'FBPLY V10 Notebook Foundation'
export const notebookCssClassName = 'notebook-system'

export const notebookBreakpoints = freeze({
  mobile: '0px',
  tablet: '640px',
  desktop: '960px',
})

export const notebookTokens = freeze({
  spacing: {
    none: '0px',
    hairline: '1px',
    xxxs: '2px',
    xxs: '4px',
    xs: '6px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    '2xl': '24px',
    '3xl': '32px',
    '4xl': '40px',
    '5xl': '56px',
  },
  paperColors: {
    white: '#fffef8',
    warm: '#fff8ec',
    cream: '#f8edd9',
    blue: '#f8fbff',
    aged: '#f7e7c6',
  },
  inkColors: {
    strong: '#111827',
    primary: '#1f2933',
    muted: '#52616f',
    subtle: '#7b8794',
    inverse: '#f8fafc',
  },
  ruledLineColors: {
    faint: '#e2edf5',
    regular: '#c7ddec',
    strong: '#8fb8d8',
    margin: '#df6b6b',
  },
  accentColors: {
    blue: '#2563eb',
    brown: '#8a5a2b',
    teal: '#256d5a',
    graphite: '#374151',
    red: '#b42318',
  },
  margins: {
    pageMobile: '16px',
    pageTablet: '24px',
    pageDesktop: '32px',
    paperMobile: '18px',
    paperTablet: '28px',
    paperDesktop: '40px',
    ruleLeftMobile: '28px',
    ruleLeftTablet: '40px',
    ruleLeftDesktop: '48px',
    ruleTop: '24px',
  },
  ruledLines: {
    compact: '24px',
    comfortable: '28px',
    relaxed: '32px',
  },
  shell: {
    maxWidth: '960px',
    ultrawideMaxWidth: '1120px',
    minWritingHeight: '336px',
    tabletMinWritingHeight: '392px',
    desktopMinWritingHeight: '448px',
    paperMinHeight: '504px',
    tabletPaperMinHeight: '560px',
    desktopPaperMinHeight: '616px',
    dateColumnWidth: '140px',
    subtitleMaxWidth: '504px',
    promptMaxWidth: '392px',
    textureSize: '4px',
    textureOpacity: '6%',
    depthOpacity: '9%',
  },
  interaction: {
    inputFontSize: '16px',
    inputLineHeight: '28px',
    inputMinHeight: '336px',
    scrollPadding: '16px',
    focusInset: '3px',
    caretColor: 'var(--nb-accent)',
  },
  radius: {
    none: '0px',
    xs: '3px',
    sm: '4px',
    md: '6px',
    lg: '8px',
  },
  elevation: {
    none: 'none',
    low: '0 4px 14px rgba(15, 23, 42, 0.06)',
    paper: '0 12px 34px rgba(15, 23, 42, 0.1)',
    lifted: '0 18px 44px rgba(15, 23, 42, 0.14)',
    inset: 'inset 0 1px 0 rgba(255, 255, 255, 0.64)',
  },
  typography: {
    heading: { fontSize: '22px', lineHeight: '28px', fontWeight: 850 },
    title: { fontSize: '28px', lineHeight: '34px', fontWeight: 900 },
    date: { fontSize: '13px', lineHeight: '18px', fontWeight: 800 },
    body: { fontSize: '15px', lineHeight: '24px', fontWeight: 500 },
    caption: { fontSize: '12px', lineHeight: '16px', fontWeight: 750 },
    amount: { fontSize: '20px', lineHeight: '26px', fontWeight: 850 },
    handwritingAccent: { fontSize: '20px', lineHeight: '28px', fontWeight: 700 },
  },
  motion: notebookMotion,
})

export const notebookResponsiveRules = freeze({
  mobile: {
    minWidth: notebookBreakpoints.mobile,
    containerPadding: notebookTokens.margins.pageMobile,
    paperPadding: notebookTokens.margins.paperMobile,
    marginRuleLeft: notebookTokens.margins.ruleLeftMobile,
    maxWidth: '100%',
  },
  tablet: {
    minWidth: notebookBreakpoints.tablet,
    containerPadding: notebookTokens.margins.pageTablet,
    paperPadding: notebookTokens.margins.paperTablet,
    marginRuleLeft: notebookTokens.margins.ruleLeftTablet,
    maxWidth: '720px',
  },
  desktop: {
    minWidth: notebookBreakpoints.desktop,
    containerPadding: notebookTokens.margins.pageDesktop,
    paperPadding: notebookTokens.margins.paperDesktop,
    marginRuleLeft: notebookTokens.margins.ruleLeftDesktop,
    maxWidth: '960px',
  },
})

export const notebookCssVariables = freeze({
  '--nb-space-0': notebookTokens.spacing.none,
  '--nb-space-hairline': notebookTokens.spacing.hairline,
  '--nb-space-xxxs': notebookTokens.spacing.xxxs,
  '--nb-space-xxs': notebookTokens.spacing.xxs,
  '--nb-space-xs': notebookTokens.spacing.xs,
  '--nb-space-sm': notebookTokens.spacing.sm,
  '--nb-space-md': notebookTokens.spacing.md,
  '--nb-space-lg': notebookTokens.spacing.lg,
  '--nb-space-xl': notebookTokens.spacing.xl,
  '--nb-space-2xl': notebookTokens.spacing['2xl'],
  '--nb-space-3xl': notebookTokens.spacing['3xl'],
  '--nb-space-4xl': notebookTokens.spacing['4xl'],
  '--nb-space-5xl': notebookTokens.spacing['5xl'],
  '--nb-paper-padding': notebookTokens.margins.paperMobile,
  '--nb-container-padding': notebookTokens.margins.pageMobile,
  '--nb-margin-rule-left': notebookTokens.margins.ruleLeftMobile,
  '--nb-margin-rule-top': notebookTokens.margins.ruleTop,
  '--nb-ruled-line-height': notebookTokens.ruledLines.comfortable,
  '--nb-shell-max-width': notebookTokens.shell.maxWidth,
  '--nb-shell-ultrawide-max-width': notebookTokens.shell.ultrawideMaxWidth,
  '--nb-shell-min-writing-height': notebookTokens.shell.minWritingHeight,
  '--nb-shell-tablet-min-writing-height': notebookTokens.shell.tabletMinWritingHeight,
  '--nb-shell-desktop-min-writing-height': notebookTokens.shell.desktopMinWritingHeight,
  '--nb-shell-paper-min-height': notebookTokens.shell.paperMinHeight,
  '--nb-shell-tablet-paper-min-height': notebookTokens.shell.tabletPaperMinHeight,
  '--nb-shell-desktop-paper-min-height': notebookTokens.shell.desktopPaperMinHeight,
  '--nb-shell-date-column-width': notebookTokens.shell.dateColumnWidth,
  '--nb-shell-subtitle-max-width': notebookTokens.shell.subtitleMaxWidth,
  '--nb-shell-prompt-max-width': notebookTokens.shell.promptMaxWidth,
  '--nb-shell-texture-size': notebookTokens.shell.textureSize,
  '--nb-shell-texture-opacity': notebookTokens.shell.textureOpacity,
  '--nb-shell-depth-opacity': notebookTokens.shell.depthOpacity,
  '--nb-input-font-size': notebookTokens.interaction.inputFontSize,
  '--nb-input-line-height': notebookTokens.interaction.inputLineHeight,
  '--nb-input-min-height': notebookTokens.interaction.inputMinHeight,
  '--nb-input-scroll-padding': notebookTokens.interaction.scrollPadding,
  '--nb-input-focus-inset': notebookTokens.interaction.focusInset,
  '--nb-input-caret-color': notebookTokens.interaction.caretColor,
  '--nb-radius-xs': notebookTokens.radius.xs,
  '--nb-radius-sm': notebookTokens.radius.sm,
  '--nb-radius-md': notebookTokens.radius.md,
  '--nb-radius-lg': notebookTokens.radius.lg,
  '--nb-shadow-none': notebookTokens.elevation.none,
  '--nb-shadow-low': notebookTokens.elevation.low,
  '--nb-shadow-paper': notebookTokens.elevation.paper,
  '--nb-shadow-lifted': notebookTokens.elevation.lifted,
  '--nb-shadow-inset': notebookTokens.elevation.inset,
  ...notebookMotionCssVariables,
})
